const GAME_STATES = {
    ENEMY_INFO: 'ENEMY_INFO',
    ENEMY_TURN: 'ENEMY_CHOOSING',
    PLAYER_TURN: 'PLAYER_TURN',
    RESULT: 'RESULT',
    VICTORY: 'VICTORY',
    LOSE: 'LOSE'
}

export default GAME_STATES;
